name: Chowkidar
release:
  chart: stakater/Chowkidar:0.0.21
  version: 0.0.21
configuration:
  chowkidar:
    controllers:
      - type: pods
        watchCriterion:
          operator: and
          identifiers:
          - "resourceExists"
          - "healthCheckExists"
        actions:
        - name: slack
          params:
            token: your-token
            channel: channel-name

    configFilePath: /configs/config.yaml
