name: Jamadar
release:
  chart: stakater/Jamadar:0.0.4
  version: 0.0.4
configuration:
  jamadar:
  namespace: default
  labels:
    provider: stakater
    group: com.stakater.platform
    version: 0.0.3
  image:
    name: stakater/jamadar
    tag: "0.0.3"
    pullPolicy: IfNotPresent
  polltimeinterval: 20m
  age: 7d
  actions:
  - name: slack
    params:
      token: <token>
      channel: <channel-name>

  configFilePath: /configs/config.yaml
